/** @type {import('tailwindcss').Config } */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,tsx}',
    './src/components/**/*.{js,ts,jsx,tsx,tsx}',
    './src/app/**/*.{js,ts,jsx,tsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#3B82F6',
        'primary-dark': '#2563EB',
        'primary-light': '#93C5FD',
        background: '#F7F7F8',
        surface: '#FFFFFF',
        border: '#E5E7EB',
        headline: '#111111',
        'body-text': '#111111',
        secondary: '#6B7280',
        'text-primary': '#111111',
        'text-secondary': '#6B7280',
        'deep-charcoal': '#1C1C1E',
        'cool-gray': '#3A3A3C',
        'off-white': '#F7F7F8',
        'pure-white': '#FFFFFF',
        'almost-black': '#111111',
        'medium-gray': '#6B7280',
        success: '#2BAE66',
        warning: '#FFB100',
        error: '#D7263D',
        info: '#007BFF',
      },
      boxShadow: {
        'shadow-sm': '0 1px 2px rgba(0, 0, 0, 0.06)',
        'shadow-md': '0 4px 6px rgba(0, 0, 0, 0.06)',
        'shadow-lg': '0 10px 15px rgba(0, 0, 0, 0.06)',
        'shadow-card': '0 2px 8px rgba(0, 0, 0, 0.06)',
      },
      spacing: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '3rem',
      },
      borderRadius: {
        'sm': '0.375rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
      },
      fontSize: {
        'xs': '0.75rem',
        'sm': '0.875rem',
        'base': '1rem',
        'lg': '1.125rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
      },
      lineHeight: {
        'tight': '1.25',
        'normal': '1.5',
        'relaxed': '1.75',
      },
      animation: {
        'spin': 'spin 1s linear infinite',
      },
    },
  },
  plugins: [],
}